/* eslint-disable */
// Generated by Wrangler
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	MONGODB_URI: string;
	JWT_SECRET: string;
	AUTH_SECRET: string;
	CRON_SECRET: string;
	NEXT_PUBLIC_APP_URL: string;
	EMAIL_FROM: string;
	WHATSAPP_API_URL: string;
	WHATSAPP_API_TOKEN: string;
	RESEND_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
